version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=healthcare
      - POSTGRES_USER=healthcare_user
      - POSTGRES_PASSWORD=passwordwanda12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
