version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=healthcare
      - POSTGRES_USER=healthcare_user
      - POSTGRES_PASSWORD=passwordwanda12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis-healthcare-booking
    ports:
      - "6391:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
    restart: always

volumes:
  postgres_data:
  redis-data:
