INSERT INTO specialization (name, description, created_at, updated_at) VALUES
('Dokter Umum', 'Spesialis yang menangani berbagai kondisi kesehatan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Anak', 'Spesialis yang fokus pada kesehatan anak-anak', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Penyakit Dalam', 'Spesialis yang menangani penyakit internal pada orang dewasa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Bedah', 'Spesialis yang melakukan prosedur pembedahan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Kandungan dan Kebidanan', 'Spesialis yang menangani kesehatan reproduksi wanita dan kehamilan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Jantung', 'Spesialis yang menangani penyakit jantung dan pembuluh darah', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Saraf', 'Spesialis yang menangani gangguan sistem saraf', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Mata', 'Spesialis kesehatan mata dan gangguan penglihatan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter THT', 'Spesialis telinga, hidung, dan tenggorokan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Kulit', 'Spesialis yang menangani masalah kulit dan kelamin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Gigi', 'Spesialis yang menangani kesehatan gigi dan mulut', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Psikiatri', 'Spesialis yang menangani kesehatan mental', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Anestesi', 'Spesialis yang menangani pengelolaan rasa sakit dan pembiusan', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Rehabilitasi Medik', 'Spesialis yang menangani pemulihan fungsi tubuh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Radiologi', 'Spesialis yang melakukan diagnosis berdasarkan hasil pencitraan medis', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Gizi Klinik', 'Spesialis yang menangani nutrisi dan diet', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Patologi Klinik', 'Spesialis yang menganalisis sampel medis dalam penyelidikan tubuh', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dokter Rehabilitasi', 'Spesialis yang membantu pemulihan pasien pasca cedera atau penyakit', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
